#!/bin/bash
#bashtest init

arg=$1

# Helper funcs
function changedir {
	cd "$1"
}

function runtestfile {
	# read -r ans
	case $arg in
    cli-3-1 ) chmod +x "${BASHDIR}/bashtests/${arg}.sh"
		"$arg.sh"
	  ;;
	cli-3-2 ) chmod +x "${BASHDIR}/bashtests/${arg}.sh"
		"$arg.sh"
	  ;;
    cli-3-3 ) chmod +x "${BASHDIR}/bashtests/${arg}.sh"
		"$arg.sh"
	  ;;
    cli-3-4 ) chmod +x "${BASHDIR}/bashtests/${arg}.sh"
		"$arg.sh"
	  ;;
	*) echo "The $arg argument can't be recognized. Try again."
	   ;;
	esac
}


if [[ -z "$arg" ]]; then
	echo "The 'bashtest' command needs an argument in order to be executed.";
else
	runtestfile
fi