#!/bin/bash
#bashtest init

arg=$1

# Helper funcs
function changedir {
	cd "$1"
}

function runtestfile {
	# read -r ans
	case $arg in
	move-test ) chmod +x "${BASHDIR}/bashtests/${arg}"
		$arg
	  ;;
    rename-test ) chmod +x "${BASHDIR}/bashtests/${arg}"
		$arg
	  ;;
    copy-test ) chmod +x "${BASHDIR}/bashtests/${arg}"
		$arg
	  ;;
    paths-test ) chmod +x "${BASHDIR}/bashtests/${arg}"
		$arg
	  ;;
	*) echo "The $arg argument can't be recognized. Try again."
	   ;;
	esac
}


if [[ -z "$arg" ]]; then
	echo "The 'bashtest' command needs an argument in order to be executed.";
else
	runtestfile
fi